### ISSUE TITLE
Suggestion: Aliases

### ISSUE THREAD

**Issue by ThatBrianDude** [linuxserver/nano-wallet#12]
Aliases are still an overlooked feature in most wallets. 

Recently vola and krypp added support for OpenCAP.  

Perhaps its a good fit for this wallet as well.

**Comment by thelamer** [comment]
We will definitely think about this as an option that can be enabled by people ingesting the wallet code for their own domains/RPC enpoints, from a stock experience at our endpoint(wallet.linuxserver.io) and for local sandboxed hosting the idea is that this wallet only communicates with the Nano node over RPC no other external services.

**Comment by thelamer** [comment]
@ThatBrianDude are there even any public OpenCap services for Nano? 
As far as I can tell it is on the Wallets to implement that server side which is kind of against the grain of a clientside wallet like this.

**Comment by ThatBrianDude** [comment]
@thelamer Currently there are two active online alias providers. (Mynano.ninja and Vola).

A clientside wallet, like you said shouldnt be an alias provider. In this case you merely resolve aliases into addresses. Being an alias provider adds the benefit of visibility for your wallet etc.. but if that isnt of sufficient value then its not necessary at all.

**Comment by thelamer** [comment]
I know it seems lazy, but couldn't an initial implementation simply have the api endpoint hard coded instead of using DNS at all? 
I understand conforming to specs and future proofing, but it seems like you could just set a list of endpoints for the TLD alias and do the get without ever hitting DNS. 
If a service pops up that proves itself as worthy of being added to that list it is low maintenance to toss it in, and people doing opencap on their own domains for single addresses would just be SOL, this would cover 99%+ of the userbase.

**Comment by thelamer** [comment]
@ThatBrianDude is there an alt URL for vola that is supposed to be used ? getvola.com does not have the server record. 

Also I don't get the whole concept it just seems like the DNS layer was added and it is an uneeded complexity. 
If the project as a whole just standardized the api path you could just toss it on a subdomain or host it on your main domain. IE for ninja: 
`https://mynano.ninja/v1/addresses?alias=my-nano-ninja$mynano.ninja&address_type=300`

From this string a user can pass `my-nano-ninja$mynano.ninja` and all the other stuff can just fill in the blanks for the js fetch, if a service is incapable of using the path `/v1/` from an infra perspective you just use a subdomain like `my-nano-ninja$oc.mynano.ninja` . 

You picking up what I am laying down here? The whole protocol seems overthought from the onset of it's implementation , just standardize the get request path/url param structure and be done with it.

**Comment by thelamer** [comment]
@ThatBrianDude I have been reading up today on this and I think ENS support makes more sense https://medium.com/the-ethereum-name-service/ens-launches-multi-coin-support-15-wallets-to-integrate-92518ab20599

It is definitely not lowering the bar in complexity but it serves to bring a decentralized backend to the naming service function. People can send some gas and have a near infallible record without depending on a centrally managed server that could potentially turn malicious (not by operators but by attack)

Has anyone in the Nanosphere looked into this ?

**Comment by thelamer** [comment]
I reached out to the ens about adding Nano to their multi coin record service and registered opencap.eth, we will see what comes of it. 
Also just noticed you created OpenCap, sorry if I was a bit harsh just speaking my mind about the protocol. 

If it is added in a best case scenario a service can be setup that takes Nano and registers subdomains to this TLD, here is an example of that process https://github.com/ensdomains/subdomain-registrar .
I have zero issues transferring the TLD to whoever wants to maintain it or maybe consider a new one. 

With a setup like this as long as the TLD keeps paying their annual fee (at this length 5 dollars) the subdomains stay permanently registered linked to the alias set by the user that sends funds.

**Comment by ThatBrianDude** [comment]
OpenCAP wasnt my idea, I was just involved early on and like to push adoption because of the obvious flaw in user experience with long addresses.

So first off I'd like to point out why we saw the need for DNS which is proxied domains. We are considering the ultra long run, there is a good reason SMTP is based on domains as well. It builds on an already well designed system. In the long run we consider proxied domains as absolutely essential. 

Many business owners will want an alias with their domain without hosting their own alias service, just like with email. 

>  just standardize the get request path/url param structure and be done with it.

This is exactly what we did. The only reason there is an extra DNS query is because of the possibility that a proxied domain isnt the opencap host itself. 

We believe its better to add an additional step then to lose the funtionality alltogether. 
Besides, when you compare opencap to e.g. openalias or other systems its by far the simplest solution. 

I kinda like your idea with the set of known hosts and honestly for the first phase of adoption it might have been a more practical solution but again, considering the long run, (I always like to refer to SMTP), its just not feasable to maintain an accurate set of hosts imo. (imagine there was an oraganisation in charge of keeping a set of email providers updated. (There are just too many).

Also to allow proxied domains you'd have to keep track of all those as well, we'd probably need an API that would allow alias providers to keep our map of proxy domains updated themselves which just seems like organisational hell alltogether.

As for ENS, this is the first time I encounter it but first up Id right away ask about scalability.. Does the alias system scale with ETH or on its own?

**Comment by thelamer** [comment]
The spec and general idea is a quick read https://docs.ens.domains/

Yeah it scales.

As for the domain proxy couldn't a business just as easily point an A record using a subdomain? that is how smtp works.

**Comment by ThatBrianDude** [comment]
Im hardly the one behind the more technical decisions so I hope Im getting this right but Im pretty sure email wouldnt be done with an A record. Wouldnt that mean you couldnt use the domain for a website at the same time? 

I think SRV records are meant for services like this

**Comment by schenkty** [comment]
Wanted to jump in here, it doesn’t make any sense to not conform to OpenCAP. OpenCAP was born out of a rift within the nano community that took months to resolve. It’s not complicated to follow the protocol and be compatible with other services on a decentralized level.

**Comment by thelamer** [comment]
@schenkty It is not about it being complicated it is about the core design of the protocol. 

Yes email is done with an A record, corps point their domains to smtp.company.com or mail.company.com it is common practice and in the case of the opencap spec simplifies the process of someone needing to point to an external service for their users to use an address with the format `alias$name.company.com` (this is even assuming they would not choose to just host it themselves)
The simplification comes in ingesting the protocol, you just hit that domain endpoint at a given URL path spec. 

You are also speaking about this protocol as if it has gained adoption since it's release which as far as I can tell it has not. There is a sole provider at https://mynano.ninja/ . Regardless of work that has been put into getting people to agree with something it is about looking years in the future about what is still going to be online. My comments revolve around the decision to use DNS at all outside of determining the host to hit to get a json payload. To me and it looks like given the current deployment space it seems like no one is adopting that layer outside of a sole entity. I am all for KISS, but in this case the value in this is a webserver spitting out a json payload given a key from a software perspective. In general there are a few things I would change about this spec just as an external observer: 

1. Drop the srv record requirement and make it optional, also documenting that it is only really needed for people that want to proxy requests to non self hosted endpoint or non standard ports (lets be real here everyone is going to put a live service on https 443)
2. Do not use a /v1 api endpoint style this is classical dev creeping into something that is brand new, still support it for legacy stuff but most users should use say /opencap as a base url and expect that to return sane payloads that could still be parsed with base keys being returned adding new ones down the line as needed
3. Do not use URL parameters and just spec out the pathing. A more sane approach would be to do a filename style or paths IE (/opencap/alias.100 up for debate) this would allow anyone with a domain even on object storage to toss a json file or set of files in a folder and tag their custom alias with no further configuration. 

It is also not inherently decentralized, it is a web 2.0 request to a webserver hosted using classical data control policies susceptible to classical attacks. 
 
What I am talking about is using a decentralized backend (eth) and a decentralized name service provider ENS to store alias records that can be ingested from main net using libraries available for a wide variety of base languages including browser javascript. 
These records are permanently stored in the blockchain using minimal gas (after a domain is setup a subdomain is about 30 cents in gas and the metadata for a nano address is 42 cents) 
There is also supported projects for running a domain reseller using this backend so minimal changes are needed if you want a central authority to say take a Nano payment and use it's own gas to register the subdomain under it's tld and store the text record (even better if ENS decides to add Nano as a multicoin supported option)
You can see an example of that here: 
https://app.ens.domains/name/opencap.eth

On the surface I don't like that just casually looking into this I discovered a standardized alias converter the rest of the cryptosphere uses and that from my side see a series of choices that do not make sense to me about how the spec is written with url params and specific server side software needing to be run to serve a json payload which could just be static.

**Comment by schenkty** [comment]
@thelamer, the aspect that you are missing here is that OpenCAP is already established. Multiple projects, both existing and upcoming, have implemented OpenCAP. I strongly reject any concept of adding decentralized backends such as ETH into a critical part of another currency. I'm frankly not sure why this is even a discussion, but feel free to use another service that is not compatible with the rest of the Nano ecosystem and burden your users.

**Comment by thelamer** [comment]
So what part of my casual spec changes do you disagree with? Do you really think the multi step DNS lookup and server operators hosting code vs just putting static json files in a folder and alias tagging being done is easier for both clients and people hosting? 

This whole spec reeks of weekend project that somehow got chosen as a standard and since inception has not made any significant changes to not break things. 

When you say Nano ecosystem do you specifically mean ninja and a single wallet?

**Comment by schenkty** [comment]
Weekend project, yikes! Insulting the community is probably not your best strategy for project adoption 😉
Numerous projects are working with OpenCAP, but I will leave it up to them to discuss their future, I would simply warn that you will be in the minority by a large margin.

**Comment by ThatBrianDude** [comment]
@thelamer What multistep DNS lookup? Its a single SRV lookup to resolve a host and a port number. 

Perhaps you are a bit confused with what is required for implementing an alias services and solely an opencap client. 

The solution you are proposing does nothing for the protocol or user experience and it would merely remove a single step from the implementation for which there already are libraries.

**Comment by thelamer** [comment]
Let's revisit this when Natrium implements it , as I see it now I don't like the idea of reaching into peoples web servers to perform an address translation , particularly on what is at it's core a client side wallet looking to be more like MEW than a native wallet utilizing contact lists and local storage locked up with a password. 
https://github.com/appditto/natrium_wallet_flutter/issues/10
It does not help that I feel like this spec will eventually be replaced/changed with something better and that decentralized naming services exist today and can be integrated with any coin to store arbitrary metadata on a blockchain somewhere.

**Comment by BitDesert** [comment]
@thelamer As you have some ideas about improving OpenCAP: Why not propose them for change?
As most crypto projects it's in an early stage, but we are all on a mission to make it accessible to everyone!
Maybe something like Email Autoconfig is the way to go, but this discussion should take place on the OpenCAP Discord or the repo.

**Comment by ThatBrianDude** [comment]
I agree, @thelamer raised some valid points that are worth discussing
